apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-frontend-config
  labels:
    app: todo-frontend
    part-of: todo-app
data:
  NEXT_PUBLIC_API_BASE_URL: "http://todo-backend:7860"
  NEXT_PUBLIC_BETTER_AUTH_URL: "http://localhost:3000"
  NEXT_PUBLIC_APP_NAME: "Todo Dashboard"
