apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
    part-of: todo-app
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30300
