apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app: todo-backend
    part-of: todo-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
